title: Arash Saeidpour 
logo: "/images/logo.png?raw=true" 
description: > # 
  First
  <br><br>
  Second
  <br><br>
  <a href="https://www.linkedin.com/in/arash-saeidpour/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
